// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: attribute_dmwg.proto

package apipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WireGuardPeerAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EndpointAddress     string `protobuf:"bytes,1,opt,name=endpoint_address,json=endpointAddress,proto3" json:"endpoint_address,omitempty"`
	EndpointPort        uint32 `protobuf:"varint,2,opt,name=endpoint_port,json=endpointPort,proto3" json:"endpoint_port,omitempty"`
	PublicKey           string `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PersistentKeepalive uint32 `protobuf:"varint,4,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
}

func (x *WireGuardPeerAttribute) Reset() {
	*x = WireGuardPeerAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attribute_dmwg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WireGuardPeerAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardPeerAttribute) ProtoMessage() {}

func (x *WireGuardPeerAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_dmwg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardPeerAttribute.ProtoReflect.Descriptor instead.
func (*WireGuardPeerAttribute) Descriptor() ([]byte, []int) {
	return file_attribute_dmwg_proto_rawDescGZIP(), []int{0}
}

func (x *WireGuardPeerAttribute) GetEndpointAddress() string {
	if x != nil {
		return x.EndpointAddress
	}
	return ""
}

func (x *WireGuardPeerAttribute) GetEndpointPort() uint32 {
	if x != nil {
		return x.EndpointPort
	}
	return 0
}

func (x *WireGuardPeerAttribute) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WireGuardPeerAttribute) GetPersistentKeepalive() uint32 {
	if x != nil {
		return x.PersistentKeepalive
	}
	return 0
}

var File_attribute_dmwg_proto protoreflect.FileDescriptor

var file_attribute_dmwg_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x64, 0x6d, 0x77, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x70, 0x69, 0x70, 0x62, 0x22, 0xba, 0x01,
	0x0a, 0x16, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x50, 0x65, 0x65, 0x72, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x65, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x65, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x31, 0x0a, 0x14, 0x70, 0x65, 0x72, 0x73, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x74, 0x4b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x72, 0x67, 0x2f, 0x67, 0x6f,
	0x62, 0x67, 0x70, 0x2f, 0x76, 0x33, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_attribute_dmwg_proto_rawDescOnce sync.Once
	file_attribute_dmwg_proto_rawDescData = file_attribute_dmwg_proto_rawDesc
)

func file_attribute_dmwg_proto_rawDescGZIP() []byte {
	file_attribute_dmwg_proto_rawDescOnce.Do(func() {
		file_attribute_dmwg_proto_rawDescData = protoimpl.X.CompressGZIP(file_attribute_dmwg_proto_rawDescData)
	})
	return file_attribute_dmwg_proto_rawDescData
}

var file_attribute_dmwg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_attribute_dmwg_proto_goTypes = []interface{}{
	(*WireGuardPeerAttribute)(nil), // 0: apipb.WireGuardPeerAttribute
}
var file_attribute_dmwg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_attribute_dmwg_proto_init() }
func file_attribute_dmwg_proto_init() {
	if File_attribute_dmwg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_attribute_dmwg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WireGuardPeerAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_attribute_dmwg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attribute_dmwg_proto_goTypes,
		DependencyIndexes: file_attribute_dmwg_proto_depIdxs,
		MessageInfos:      file_attribute_dmwg_proto_msgTypes,
	}.Build()
	File_attribute_dmwg_proto = out.File
	file_attribute_dmwg_proto_rawDesc = nil
	file_attribute_dmwg_proto_goTypes = nil
	file_attribute_dmwg_proto_depIdxs = nil
}
